# Generated by Django 4.1.5 on 2023-03-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='price',
            new_name='startingPrice',
        ),
    ]
