# Generated by Django 4.1.5 on 2023-03-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_rename_price_posts_startingprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='startingPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
